### ISSUE TITLE
로그인 버그

### ISSUE THREAD

**Issue by Epikem** [pseudolab/PseudoBack#44]
- cush.kr에서 로그인이 제대로 되지 않는 문제 발생

**Comment by seriousran** [comment]
로컬에서는 동작하지만, cush.kr 에서는 동작되지 않음.
- nginx로 serving하는 것과 nuxt를 통해 npm run start로 서빙하는 것 두 경우 모두에서 작동 X

**Comment by Epikem** [comment]
링크된 풀리퀘스트 기준으로도 동작안하나요??
디비연결이 되지 않을때 그냥 멈추는거같아서 관련 로그 출력을 추가했는데 한번 로그 확인 부탁드려요
